name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write       # ✅ 允许写 tag、写 changelog
  pull-requests: write  # ✅ 允许创建 PR

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Release Please
        uses: googleapis/release-please-action@v4  # ✅ 已修正 deprecated
        with:
          release-type: simple
